version: '3'

services:
  farmtopia-portal:
    build:
      context: .
      dockerfile: Dockerfile
    image: farmtopia-portal
    ports:
      - 3002:3000
    container_name: farmtopia-portal
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: ${HOST}
      VIRTUAL_PORT: 3002
      LETSENCRYPT_HOST: ${HOST}
      LETSENCRYPT_EMAIL: mohamedamal680@gmail.com
networks:
  default:
    external:
      name: nginx-proxy

